// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// aliasRemover is an autogenerated mock type for the aliasRemover type
type aliasRemover struct {
	mock.Mock
}

// DeleteAlias provides a mock function with given fields: alias
func (_m *aliasRemover) DeleteAlias(alias string) error {
	ret := _m.Called(alias)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(alias)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewAliasRemover interface {
	mock.TestingT
	Cleanup(func())
}

// newAliasRemover creates a new instance of aliasRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newAliasRemover(t mockConstructorTestingTnewAliasRemover) *aliasRemover {
	mock := &aliasRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
