// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AliasRemover is an autogenerated mock type for the AliasRemover type
type AliasRemover struct {
	mock.Mock
}

// DeleteAlias provides a mock function with given fields: alias
func (_m *AliasRemover) DeleteAlias(alias string) error {
	ret := _m.Called(alias)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(alias)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAliasRemover interface {
	mock.TestingT
	Cleanup(func())
}

// NewAliasRemover creates a new instance of AliasRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAliasRemover(t mockConstructorTestingTNewAliasRemover) *AliasRemover {
	mock := &AliasRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
