env: 'prod'
storage_path: 'postgres://tester:pop123@localhost:5432/test'
gin_mode: 'release'
alias_length: 8
http_server:
    address: 'localhost:8080'
    timeout: 4s
    idle_timeout: 60s
    user: 'pedro'
    password: 'd123'
